set_property PACKAGE_PIN H5 [get_ports LED1]
set_property PACKAGE_PIN J5 [get_ports LED2]
set_property PACKAGE_PIN T9 [get_ports LED3]
set_property PACKAGE_PIN T10 [get_ports LED4]

set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED4]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
