# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.cache/wt [current_project]
set_property parent.project_path C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/ip_repo_git [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/hdl/DMF_Translation_wrapper.v
add_files C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/DMF_Translation.bd
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_microblaze_0_0/DMF_Translation_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_microblaze_0_0/DMF_Translation_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_microblaze_0_0/DMF_Translation_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_dlmb_v10_0/DMF_Translation_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_dlmb_v10_0/DMF_Translation_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_ilmb_v10_0/DMF_Translation_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_ilmb_v10_0/DMF_Translation_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_dlmb_bram_if_cntlr_0/DMF_Translation_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_ilmb_bram_if_cntlr_0/DMF_Translation_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_lmb_bram_0/DMF_Translation_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_mdm_1_0/DMF_Translation_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_mdm_1_0/DMF_Translation_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_clk_wiz_1_0/DMF_Translation_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_clk_wiz_1_0/DMF_Translation_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_clk_wiz_1_0/DMF_Translation_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_rst_clk_wiz_1_100M_0/DMF_Translation_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_rst_clk_wiz_1_100M_0/DMF_Translation_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_rst_clk_wiz_1_100M_0/DMF_Translation_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_uartlite_0_0/DMF_Translation_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_uartlite_0_0/DMF_Translation_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_uartlite_0_0/DMF_Translation_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_ethernetlite_0_0/DMF_Translation_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_ethernetlite_0_0/DMF_Translation_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_ethernetlite_0_0/DMF_Translation_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_ethernetlite_0_0/DMF_Translation_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_xbar_0/DMF_Translation_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_intc_0_0/DMF_Translation_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_intc_0_0/DMF_Translation_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_intc_0_0/DMF_Translation_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_mig_7series_0_1/DMF_Translation_mig_7series_0_1/user_design/constraints/DMF_Translation_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_mig_7series_0_1/DMF_Translation_mig_7series_0_1/user_design/constraints/DMF_Translation_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_mig_7series_0_1/DMF_Translation_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_timer_0_0/DMF_Translation_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_axi_timer_0_0/DMF_Translation_axi_timer_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_1/DMF_Translation_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_1/DMF_Translation_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_1/DMF_Translation_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_0/DMF_Translation_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_0/DMF_Translation_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_0/DMF_Translation_auto_ds_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_1/DMF_Translation_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_1/DMF_Translation_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_1/DMF_Translation_auto_ds_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_2/DMF_Translation_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_2/DMF_Translation_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_2/DMF_Translation_auto_ds_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_3/DMF_Translation_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_3/DMF_Translation_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_3/DMF_Translation_auto_ds_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_4/DMF_Translation_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_4/DMF_Translation_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_4/DMF_Translation_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_pc_0/DMF_Translation_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_0/DMF_Translation_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_0/DMF_Translation_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_us_0/DMF_Translation_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_5/DMF_Translation_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_5/DMF_Translation_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_auto_ds_5/DMF_Translation_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/DMF_Translation_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/sources_1/bd/DMF_Translation/ip/DMF_Translation_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/constrs_1/new/eth_ref_clk.xdc
set_property used_in_implementation false [get_files C:/Users/FemtoFluidics/Documents/GitHub/vivadoRepository1/glue/glue.srcs/constrs_1/new/eth_ref_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DMF_Translation_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DMF_Translation_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DMF_Translation_wrapper_utilization_synth.rpt -pb DMF_Translation_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
