# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/DMF_Translation/DMF_Translation.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation || ORIG_REF_NAME==DMF_Translation} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_microblaze_0_0/DMF_Translation_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_microblaze_0_0 || ORIG_REF_NAME==DMF_Translation_microblaze_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_dlmb_v10_0/DMF_Translation_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_dlmb_v10_0 || ORIG_REF_NAME==DMF_Translation_dlmb_v10_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_ilmb_v10_0/DMF_Translation_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_ilmb_v10_0 || ORIG_REF_NAME==DMF_Translation_ilmb_v10_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_dlmb_bram_if_cntlr_0/DMF_Translation_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DMF_Translation_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_ilmb_bram_if_cntlr_0/DMF_Translation_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DMF_Translation_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_lmb_bram_0/DMF_Translation_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_lmb_bram_0 || ORIG_REF_NAME==DMF_Translation_lmb_bram_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_mdm_1_0/DMF_Translation_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_mdm_1_0 || ORIG_REF_NAME==DMF_Translation_mdm_1_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_clk_wiz_1_0/DMF_Translation_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_clk_wiz_1_0 || ORIG_REF_NAME==DMF_Translation_clk_wiz_1_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_rst_clk_wiz_1_100M_0/DMF_Translation_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DMF_Translation_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_axi_uartlite_0_0/DMF_Translation_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_axi_uartlite_0_0 || ORIG_REF_NAME==DMF_Translation_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_axi_ethernetlite_0_0/DMF_Translation_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_axi_ethernetlite_0_0 || ORIG_REF_NAME==DMF_Translation_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_logicDMF_0_0/DMF_Translation_logicDMF_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_logicDMF_0_0 || ORIG_REF_NAME==DMF_Translation_logicDMF_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_xbar_0/DMF_Translation_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_xbar_0 || ORIG_REF_NAME==DMF_Translation_xbar_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_DMF_processor_axi_periph_0/DMF_Translation_DMF_processor_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_DMF_processor_axi_periph_0 || ORIG_REF_NAME==DMF_Translation_DMF_processor_axi_periph_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_axi_intc_0_0/DMF_Translation_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_axi_intc_0_0 || ORIG_REF_NAME==DMF_Translation_axi_intc_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_mig_7series_0_1/DMF_Translation_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_mig_7series_0_1 || ORIG_REF_NAME==DMF_Translation_mig_7series_0_1} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_axi_timer_0_0/DMF_Translation_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_axi_timer_0_0 || ORIG_REF_NAME==DMF_Translation_axi_timer_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_xlconcat_0_0/DMF_Translation_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_xlconcat_0_0 || ORIG_REF_NAME==DMF_Translation_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_us_1/DMF_Translation_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_us_1 || ORIG_REF_NAME==DMF_Translation_auto_us_1} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_0/DMF_Translation_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_0 || ORIG_REF_NAME==DMF_Translation_auto_ds_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_1/DMF_Translation_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_1 || ORIG_REF_NAME==DMF_Translation_auto_ds_1} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_2/DMF_Translation_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_2 || ORIG_REF_NAME==DMF_Translation_auto_ds_2} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_3/DMF_Translation_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_3 || ORIG_REF_NAME==DMF_Translation_auto_ds_3} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_4/DMF_Translation_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_4 || ORIG_REF_NAME==DMF_Translation_auto_ds_4} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_pc_0/DMF_Translation_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_pc_0 || ORIG_REF_NAME==DMF_Translation_auto_pc_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_us_0/DMF_Translation_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_us_0 || ORIG_REF_NAME==DMF_Translation_auto_us_0} -quiet] -quiet

# IP: bd/DMF_Translation/ip/DMF_Translation_auto_ds_5/DMF_Translation_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMF_Translation_auto_ds_5 || ORIG_REF_NAME==DMF_Translation_auto_ds_5} -quiet] -quiet

# XDC: bd/DMF_Translation/DMF_Translation_ooc.xdc
